### ISSUE TITLE
Node-Sass not installing properly

### ISSUE THREAD

**Issue by dlaufer** [bluecadet/cadet#8]
I created a new site with `cadet` and tried to run `gulp fractal`, but got this error:

![Screen Shot 2020-02-28 at 10 55 03 AM](https://user-images.githubusercontent.com/5403982/75563768-e3748280-5a18-11ea-8155-332961b815fa.png)

The solution: https://github.com/sass/node-sass/issues/1579. This was resolved by running `npm rebuild node-sass` so we should add this to the tool or figure out if this is resolved in newer versions.

**Comment by pingevt** [comment]
@dlaufer 

Just double checking, but we don't have any npm commands in our docs... what exactly did you run before you saw the error? 

I've run into this before too but I thought it was because I change my node versions a lot. So may be more of an issue than i thought previously.


Also, the npm/sass/gulp/stuff should also be logged in the themes repo: https://github.com/bluecadet/bc-base-themes

`cadet` should not really care about the theme stuff at all...

**Comment by dlaufer** [comment]
@pingevt I'm pretty sure that was the first thing I tried to do after finishing the instructions from the cadet README. I may have run an "npm install" beforehand.

**Comment by pingevt** [comment]
gotcha - we could probably add more of those steps to the readme so we are _completely_ ready to develop on a project.

**Comment by dlaufer** [comment]
This was due to having "ignore-scripts" set globally in my `~/.npmrc` file.
